import "@/styles/globals.css";
import Layout from "@/components/layouts/Layout";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
  <>
      <Head>
        <title>UzimaNexusHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head> 
    <Layout >
      <Component {...pageProps} />
    </Layout>
  </>
  )
}
